/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

/**
 *
 * @author 9FDAM09
 */
public class PaguinaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaguinaPrincipal
     */
    public PaguinaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        boton1 = new javax.swing.JPanel();
        labelBoton1 = new javax.swing.JLabel();
        boton2 = new javax.swing.JPanel();
        labelBoton2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(114, 70, 124));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setBackground(new java.awt.Color(198, 177, 201));

        labelBoton1.setForeground(new java.awt.Color(0, 0, 0));
        labelBoton1.setText("Boton1");

        javax.swing.GroupLayout boton1Layout = new javax.swing.GroupLayout(boton1);
        boton1.setLayout(boton1Layout);
        boton1Layout.setHorizontalGroup(
            boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labelBoton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        boton1Layout.setVerticalGroup(
            boton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelBoton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelMenu.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, -1));

        boton2.setBackground(new java.awt.Color(198, 177, 201));

        labelBoton2.setForeground(new java.awt.Color(0, 0, 0));
        labelBoton2.setText("Boton1");

        javax.swing.GroupLayout boton2Layout = new javax.swing.GroupLayout(boton2);
        boton2.setLayout(boton2Layout);
        boton2Layout.setHorizontalGroup(
            boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(labelBoton2)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        boton2Layout.setVerticalGroup(
            boton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelBoton2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelMenu.add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaguinaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaguinaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaguinaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaguinaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaguinaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boton1;
    private javax.swing.JPanel boton2;
    private javax.swing.JLabel labelBoton1;
    private javax.swing.JLabel labelBoton2;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
