/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import consultas.ConsultasGestion;
import hibernate.GestionEntity;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author omega
 */
public class PanelEstadisticas extends javax.swing.JPanel {
    JPanel content;
    /**
     * Creates new form PanelEstadistics
     */
    public PanelEstadisticas(JPanel content) {
        initComponents();
        this.content = content;

        //cargar datos
        ConsultasGestion con = new ConsultasGestion();
        List<GestionEntity> relaciones = con.recuperarGestionGeneral();
        con.cerrarConexion();
        //recuperar pieza mas suministrada
        int cantidad = 0;
        int cantidadpro = 0;
        String cod = null;
        for (int i = 0; i < relaciones.size(); i++) {
            for (GestionEntity relacione : relaciones) {
                if (relaciones.get(i).getPiezasByCodpieza().getCodpiezas().equals(relacione.getPiezasByCodpieza().getCodpiezas())) {
                    cantidadpro = cantidadpro + relacione.getCantidad();
                }
            }
            if (cantidad < cantidadpro) {
                cantidad = cantidadpro;
                cod = relaciones.get(i).getPiezasByCodpieza().getCodpiezas();
            }
            cantidadpro = 0;
        }
        labelPiezasMas.setText("Pieza de la que se ha suministrado mas cantidad: " + cod + " - " + cantidad);
        cantidad = 0;
        cod = null;
        //pieza que se ha suministrado a mas proyectos
        for (int i = 0; i < relaciones.size(); i++) {
            for (GestionEntity relacione : relaciones) {
                if (relaciones.get(i).getPiezasByCodpieza().getCodpiezas().equals(relacione.getPiezasByCodpieza().getCodpiezas())) {
                    cantidadpro = cantidadpro + 1;
                }
            }
            if (cantidad < cantidadpro) {
                cantidad = cantidadpro;
                cod = relaciones.get(i).getPiezasByCodpieza().getCodpiezas();
            }
            cantidadpro = 0;
        }
        labelPiezasProyecto.setText("Pieza que se ha suministrado a mas proyectos: " + cod + " - " + cantidad);
        cantidad = 0;
        cod = null;
        //proveedor que ha suministrado mas cantidad de piezas
        for (int i = 0; i < relaciones.size(); i++) {
            for (GestionEntity relacione : relaciones) {
                if (relaciones.get(i).getProveedoresByCodproveedor().getCodprov().equals(relacione.getProveedoresByCodproveedor().getCodprov())) {
                    cantidadpro = cantidadpro + relacione.getCantidad();
                }
            }
            if (cantidad < cantidadpro) {
                cantidad = cantidadpro;
                cod = relaciones.get(i).getProveedoresByCodproveedor().getCodprov();
            }
            cantidadpro = 0;
        }
        labelProveedorPiezasCantidad.setText("Proveedor que ha suministrado mas cantidad de piezas " + cod  + " - " + cantidad);
        cantidad = 0;
        cod = null;
        //proveedor que ha suministrado a mas proyectos
        for (int i = 0; i < relaciones.size(); i++) {
            for (GestionEntity relacione : relaciones) {
                if (relaciones.get(i).getProveedoresByCodproveedor().getCodprov().equals(relacione.getProveedoresByCodproveedor().getCodprov())) {
                    cantidadpro = cantidadpro + 1;
                }
            }
            if (cantidad < cantidadpro) {
                cantidad = cantidadpro;
                cod = relaciones.get(i).getProveedoresByCodproveedor().getCodprov();
            }
            cantidadpro = 0;
        }
        labelProveedorProyectosMax.setText("Proveedor que ha suministrado a mas proyectos: " + cod  + " - " + cantidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPiezasMas = new javax.swing.JLabel();
        labelPiezasProyecto = new javax.swing.JLabel();
        labelProveedorPiezasCantidad = new javax.swing.JLabel();
        labelProveedorProyectosMax = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPiezasMas.setForeground(new java.awt.Color(0, 0, 0));
        labelPiezasMas.setText("Pieza de la que se ha suministrado mas cantidad: ");
        add(labelPiezasMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 610, 30));

        labelPiezasProyecto.setForeground(new java.awt.Color(0, 0, 0));
        labelPiezasProyecto.setText("Pieza que se ha suministrado a mas proyectos:");
        add(labelPiezasProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 610, 30));

        labelProveedorPiezasCantidad.setForeground(new java.awt.Color(0, 0, 0));
        labelProveedorPiezasCantidad.setText("Proveedor que ha suministrado mas cantidad de piezas");
        add(labelProveedorPiezasCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 610, 30));

        labelProveedorProyectosMax.setForeground(new java.awt.Color(0, 0, 0));
        labelProveedorProyectosMax.setText("Proveedor que ha suministrado a mas proyectos:");
        add(labelProveedorProyectosMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 610, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPiezasMas;
    private javax.swing.JLabel labelPiezasProyecto;
    private javax.swing.JLabel labelProveedorPiezasCantidad;
    private javax.swing.JLabel labelProveedorProyectosMax;
    // End of variables declaration//GEN-END:variables
}
