/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.BorderLayout;

/**
 *
 * @author omega
 */
public class PanelMenuProyectos extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuProyectos
     */
    public PanelMenuProyectos() {
        initComponents();
        
        PanelGestionProyectos frame = new PanelGestionProyectos();
        frame.setSize(830,490);
        frame.setLocation(0,0);
        content.removeAll();
        content.add(frame, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuTop = new javax.swing.JPanel();
        botonNuevoProyecto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonGestionProyectos = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuTop.setBackground(new java.awt.Color(114, 70, 124));
        panelMenuTop.setMinimumSize(new java.awt.Dimension(830, 60));

        botonNuevoProyecto.setBackground(new java.awt.Color(114, 70, 124));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nuevo Proyecto");

        javax.swing.GroupLayout botonNuevoProyectoLayout = new javax.swing.GroupLayout(botonNuevoProyecto);
        botonNuevoProyecto.setLayout(botonNuevoProyectoLayout);
        botonNuevoProyectoLayout.setHorizontalGroup(
            botonNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonNuevoProyectoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        botonNuevoProyectoLayout.setVerticalGroup(
            botonNuevoProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonNuevoProyectoLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        botonGestionProyectos.setBackground(new java.awt.Color(198, 177, 201));

        javax.swing.GroupLayout botonGestionProyectosLayout = new javax.swing.GroupLayout(botonGestionProyectos);
        botonGestionProyectos.setLayout(botonGestionProyectosLayout);
        botonGestionProyectosLayout.setHorizontalGroup(
            botonGestionProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        botonGestionProyectosLayout.setVerticalGroup(
            botonGestionProyectosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuTopLayout = new javax.swing.GroupLayout(panelMenuTop);
        panelMenuTop.setLayout(panelMenuTopLayout);
        panelMenuTopLayout.setHorizontalGroup(
            panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTopLayout.createSequentialGroup()
                .addComponent(botonGestionProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 514, Short.MAX_VALUE))
        );
        panelMenuTopLayout.setVerticalGroup(
            panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTopLayout.createSequentialGroup()
                .addGroup(panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonNuevoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonGestionProyectos;
    private javax.swing.JPanel botonNuevoProyecto;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelMenuTop;
    // End of variables declaration//GEN-END:variables
}
