/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import consultas.ConsultasProveedores;

import javax.swing.*;
import java.awt.*;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * @author 9FDAM09
 */
public class PanelNuevoProveedor extends javax.swing.JPanel {
    JPanel content = null;

    /**
     * Creates new form NuevoProveedor
     */
    public PanelNuevoProveedor(JPanel content) {
        initComponents();
        this.content = content;
    }

    public void anadirProveedor() {
        ConsultasProveedores con = new ConsultasProveedores();
        if (con.anadirProveedor(codField.getText().toUpperCase(), nombreField.getText(), apellidoField.getText(), direccionField.getText())) {
            codField.setText("");
            nombreField.setText("");
            apellidoField.setText("");
            direccionField.setText("");
        }
        con.cerrarConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        apellidoField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        direccionField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botonAnadir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        botonLimpiar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 70, 30));

        nombreField.setBackground(new java.awt.Color(204, 204, 204));
        nombreField.setForeground(new java.awt.Color(0, 0, 0));
        nombreField.setBorder(null);
        add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 350, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUEVO PROVEEDOR");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 350, -1));

        apellidoField.setBackground(new java.awt.Color(204, 204, 204));
        apellidoField.setForeground(new java.awt.Color(0, 0, 0));
        apellidoField.setBorder(null);
        add(apellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 350, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 70, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 350, -1));

        direccionField.setBackground(new java.awt.Color(204, 204, 204));
        direccionField.setForeground(new java.awt.Color(0, 0, 0));
        direccionField.setBorder(null);
        add(direccionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 330, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direcccion: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 100, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 330, -1));

        botonAnadir.setBackground(new java.awt.Color(57, 57, 58));
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAnadirMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 219, 219));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("AÑADIR PROVEEDOR");

        javax.swing.GroupLayout botonAnadirLayout = new javax.swing.GroupLayout(botonAnadir);
        botonAnadir.setLayout(botonAnadirLayout);
        botonAnadirLayout.setHorizontalGroup(
            botonAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonAnadirLayout.setVerticalGroup(
            botonAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonAnadirLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        add(botonAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, 50));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Codigo: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 70, 30));

        codField.setBackground(new java.awt.Color(204, 204, 204));
        codField.setForeground(new java.awt.Color(0, 0, 0));
        codField.setBorder(null);
        add(codField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 350, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 350, -1));

        botonLimpiar.setBackground(new java.awt.Color(57, 57, 58));
        botonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLimpiarMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(219, 219, 219));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LIMPIAR");

        javax.swing.GroupLayout botonLimpiarLayout = new javax.swing.GroupLayout(botonLimpiar);
        botonLimpiar.setLayout(botonLimpiarLayout);
        botonLimpiarLayout.setHorizontalGroup(
            botonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonLimpiarLayout.setVerticalGroup(
            botonLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonLimpiarLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMousePressed
        if (codField.getText().isBlank() || nombreField.getText().isBlank() || apellidoField.getText().isBlank() || direccionField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos para poder añadir un proveedor.");
        } else {
            Pattern pattern = Pattern.compile("^([A-Za-z]{2}[0-9]{4})$");
            Matcher codPattern = pattern.matcher(codField.getText());
            if (codPattern.find()) {
                anadirProveedor();
            } else {
                JOptionPane.showMessageDialog(null, "Error para escribir el codigo tiene que contener 2 letras y 4 numeros.");
            }
        }
    }//GEN-LAST:event_botonAnadirMousePressed

    private void botonLimpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLimpiarMousePressed
        nombreField.setText("");
        apellidoField.setText("");
        direccionField.setText("");
        codField.setText("");
    }//GEN-LAST:event_botonLimpiarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoField;
    private javax.swing.JPanel botonAnadir;
    private javax.swing.JPanel botonLimpiar;
    private javax.swing.JTextField codField;
    private javax.swing.JTextField direccionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreField;
    // End of variables declaration//GEN-END:variables
}
