/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author omega
 */
public class PanelMenuPiezas extends javax.swing.JPanel {
    /**
     * Creates new form PanelMenuPiezas
     */
    public PanelMenuPiezas() {
        initComponents();
        
        PanelGestionPiezas frame = new PanelGestionPiezas(content);
        frame.setSize(830,490);
        frame.setLocation(0,0);
        content.removeAll();
        content.add(frame, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuTop = new javax.swing.JPanel();
        botonGestionPiezas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonNuevaPieza = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(830, 550));
        setPreferredSize(new java.awt.Dimension(830, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuTop.setBackground(new java.awt.Color(114, 70, 124));
        panelMenuTop.setPreferredSize(new java.awt.Dimension(830, 60));

        botonGestionPiezas.setBackground(new java.awt.Color(198, 177, 201));
        botonGestionPiezas.setPreferredSize(new java.awt.Dimension(155, 60));
        botonGestionPiezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonGestionPiezasMousePressed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestion de piezas");

        javax.swing.GroupLayout botonGestionPiezasLayout = new javax.swing.GroupLayout(botonGestionPiezas);
        botonGestionPiezas.setLayout(botonGestionPiezasLayout);
        botonGestionPiezasLayout.setHorizontalGroup(
            botonGestionPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGestionPiezasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        botonGestionPiezasLayout.setVerticalGroup(
            botonGestionPiezasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonGestionPiezasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        botonNuevaPieza.setBackground(new java.awt.Color(114, 70, 124));
        botonNuevaPieza.setPreferredSize(new java.awt.Dimension(155, 60));
        botonNuevaPieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonNuevaPiezaMousePressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Añadir Pieza");

        javax.swing.GroupLayout botonNuevaPiezaLayout = new javax.swing.GroupLayout(botonNuevaPieza);
        botonNuevaPieza.setLayout(botonNuevaPiezaLayout);
        botonNuevaPiezaLayout.setHorizontalGroup(
            botonNuevaPiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonNuevaPiezaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        botonNuevaPiezaLayout.setVerticalGroup(
            botonNuevaPiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonNuevaPiezaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMenuTopLayout = new javax.swing.GroupLayout(panelMenuTop);
        panelMenuTop.setLayout(panelMenuTopLayout);
        panelMenuTopLayout.setHorizontalGroup(
            panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTopLayout.createSequentialGroup()
                .addComponent(botonGestionPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonNuevaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        panelMenuTopLayout.setVerticalGroup(
            panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuTopLayout.createSequentialGroup()
                .addGroup(panelMenuTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGestionPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelMenuTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionPiezasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGestionPiezasMousePressed
        setColor(botonGestionPiezas);
        resetColor(botonNuevaPieza);
                
        PanelGestionPiezas frame = new PanelGestionPiezas(content);
        frame.setSize(830,490);
        frame.setLocation(0,0);
        content.removeAll();
        content.add(frame, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_botonGestionPiezasMousePressed

    private void botonNuevaPiezaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevaPiezaMousePressed
        setColor(botonNuevaPieza);
        resetColor(botonGestionPiezas);
                
        PanelNuevaPieza frame = new PanelNuevaPieza();
        frame.setSize(830,490);
        frame.setLocation(0,0);
        content.removeAll();
        content.add(frame, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_botonNuevaPiezaMousePressed

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(198,177,201));
    }
    
    private void resetColor(JPanel pane) {
        pane.setBackground(new Color(114,70,124));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonGestionPiezas;
    private javax.swing.JPanel botonNuevaPieza;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelMenuTop;
    // End of variables declaration//GEN-END:variables
}
